title: Code Kyo
description: Programming and the curiosity behind it.

url: https://codekyo.me
baseurl: ""
paginate_path: "page:num/"
permalink: :title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: brennanbrown
   twitter: brennankbrown
   facebook: brennan.k.brown
   email: mail@codekyo.me

google_analytics: "UA-58263416-1"
